development:
  login: 'login'
  password: 'password'
  signature: 'signature'
production:
  login: 'login'
  password: 'password'
  signature: 'signature'
test:
  login: 'login'
  password: 'password'
  signature: 'signature'
  